version: "3.3"

services:
  demo:
    build: .
    command: java -classpath build/classes/java/main se.king.mehdi.CmdLineDemo
    tty: true
    stdin_open: true
    container_name: anagram_demo

  tests:
    build: .
    command: ./gradlew --no-daemon clean test
    container_name: anagram_tests
